#ifndef __structuredquerycondition_h__
#define __structuredquerycondition_h__
typedef enum tagCONDITION_TYPE { CT_AND_CONDITION=0, CT_OR_CONDITION, CT_NOT_CONDITION, CT_LEAF_CONDITION } CONDITION_TYPE;
typedef enum tagCONDITION_OPERATION { COP_IMPLICIT=0, COP_EQUAL, COP_NOTEQUAL, COP_LESSTHAN, COP_GREATERTHAN, COP_LESSTHANOREQUAL, COP_GREATERTHANOREQUAL, COP_VALUE_STARTSWITH, COP_VALUE_ENDSWITH, COP_VALUE_CONTAINS, COP_VALUE_NOTCONTAINS, COP_DOSWILDCARDS, COP_WORD_EQUAL, COP_WORD_STARTSWITH, COP_APPLICATION_SPECIFIC } CONDITION_OPERATION;
#endif
